[tool.poetry]
name = "sciencenerds"
version = "0.1.0"
description = ""
authors = ["Brenda <mejiab19@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.1"
dj-database-url = "^2.1.0"
djangorestframework = "^3.14.0"
pillow = "^10.2.0"
django-filter = "^23.5"
psycopg2-binary = "^2.9.9"
whitenoise = {extras = ["brotli"], version = "^6.6.0"}
gunicorn = "^21.2.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
